### ISSUE TITLE
very well done

### ISSUE THREAD

**Issue by puyagithub** [AzadNetCH/Clash#20]
keep it up & find other nerds to grow this project until no ISP can throttle, censored and block us. I can't code but I'm willing to help however I can. I can spread the word and provide tutorial. I can even design logo or something for this project.
the issue I'm here to report is this error when I try your META_Iran profile. what is it?
![image](https://github.com/AzadNetCH/Clash/assets/4789535/6fbe927c-69d2-4229-835e-60dc8c4cb7e8)

**Comment by AzadNetCH** [comment]
Thank you for your support.
The reason for this error is the lack of support for the Vless type in that software. For example, the URL you entered is only suitable for Clash Meta, and it gives an error in the Clash.
