### ISSUE TITLE
Important Issue!

### ISSUE THREAD

**Issue by Shikopat** [AzadNetCH/Clash#3]
There's some **Chinese DNS** at :
https://github.com/AzadNetCH/Clash/blob/main/AzadNet.yml

You **only** need these DNS for **nameserver** & **fallback**:
tls://dns.google:853
https://dns.google/dns-query
https://cloudflare-dns.com/dns-query
https://dns.adguard.com/dns-query
https://dnsforge.de/dns-quer
https://dns.quad9.net/dns-query

**Comment by AzadNetCH** [comment]
Thank you for your attention. The bugs in the configuration have been fixed.
