### ISSUE TITLE
اشکال در تایپ دی ان اس

### ISSUE THREAD

**Issue by Gherkashen2** [AzadNetCH/Clash#4]
با درود

لطفا در کانفیگ های زیر دی ان اس
https://dnsforge.de/dns-quer
را به
https://dnsforge.de/dns-query
تغییر دهید.تشکر

**Comment by AzadNetCH** [comment]
با درود و سپاس از دقت نظر شما
اشتباه تایپی مورد نظر برطرف شد

شاد و تندرست باشید
