### ISSUE TITLE
رفع مشکل کلش در ارتباط با کال و وویس چت تلگرام

### ISSUE THREAD

**Issue by Gherkashen2** [AzadNetCH/Clash#5]
با درود
در انتهای برخی سرور های شدوساکس کلش، عبارت
, udp: true
وجود دارد که آن سرور ها مناسب برای تماس تلگرام یا وویس چت می باشد
لذا بهتر است انتهای تمامی سرور های شدوساکس کانفیگ ها ،عبارت فوق الصاق شود 
پس از اعمال تغییرات،کانفیگ در کلش اندروید و ساگرنت کماکان قابل ایمپورت است.
تشکر

درمورد vmess هایی 
که این عبارت را ندارند، نیز صادق است! 
برای تایید و صحت سنجی ادعا می توانید امتحان کنید!

**Comment by AzadNetCH** [comment]
![IMG_20210719_132511_205](https://user-images.githubusercontent.com/75164819/126132609-6e2437bd-6302-4c62-9b6b-0389f15376d6.jpg)
بله، در آپدیت بعدی، پس از اصلاح آی‌پی تمام سرورها، این تغییر رو هم اعمال می‌کنیم
سپاسگزارم
