### ISSUE TITLE
بهبود عملکرد

### ISSUE THREAD

**Issue by Gherkashen2** [AzadNetCH/Clash#6]
درود
در کانفیگ AzadNet--Iran-Direct 1.yml
بهتر است به جای quad9
از مورد زیر استفاده گردد چرا که برخی اپراتور ها با ان مشکل دارند:
https://cloudflare-dns.com/dns-query

**Comment by AzadNetCH** [comment]
تغییر پیشنهادی شما اِعمال گردید
با سپاس
